version: "3"

services:
  dash:
    hostname: dash
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/wd/src
    environment:
      - PORT=8080
    command: gunicorn --workers=5 --threads=1 -b 0.0.0.0:80 app:server
    restart: unless-stopped