version: "3"

services:
  dash:
    hostname: dash
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/wd/src
    environment:
      - PORT=8080
    command: gunicorn --workers=5 --threads=1 -b 0.0.0.0:80 app:server
    depends_on:
      - neo4j
    restart: unless-stopped
    networks:
      - neo4j_net
  neo4j:
      image: neo4j:latest
      hostname: neo4j
      restart: unless-stopped
      ports:
      - 7474:7474
      - 7687:7687
      volumes:
      - ./neo4j/data:/data
      - ./logs:/logs
      environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/password
      networks:
      - neo4j_net
volumes:
    neo4j_data:
    neo4j_import:
networks:
    neo4j_net:
      driver: bridge