version: "3"

services:
 neo4j:
      image: neo4j:latest
      hostname: neo4j
      restart: unless-stopped
      ports:
      - 7474:7474
      - 7687:7687
      volumes:
      - ./neo4j/data:/data
      - ./logs:/logs
      environment:
      - NEO4J_AUTH=neo4j/password
      
volumes:
    neo4j_data:
    neo4j_logs: