version: "3"

services:
  dash:
    hostname: dash
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/wd/src
    environment:
      - PORT=8080
      - URL=neo4j://10.210.20.50:30770
      - USERNAME=neo4j
      - PASSWORD=i2c_@2lletas_09!

    command: gunicorn --workers=5 --threads=1 -b 0.0.0.0:8080 app:server
