name: Deployment

on:
  push:
    branches:
      - master

env:
  DOCKER_COMPOSE_VERSION: 1.27.4

jobs:
  deploy:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v2
        - name: Build the stack
          run: 
            sudo docker-compose build 
            sudo docker-compose up -d 