name: Deployment

on:
  push:
    branches:
      - master

env:
  DOCKER_COMPOSE_VERSION: 1.27.4

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Load Data 
      run: |
        chmod +x init.sh && ./init.sh

    - name: Deploy with Docker Compose
      run: |
        docker-compose up -d