
name: Deployment

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v2
        - name: Build 
          run: 
            docker-compose build 
        - name: UpCompose
          run: docker-compose up -d
