
name: Deployment

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v3
        - name: Install Docker Compose
          run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.15.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
            sudo echo "export PATH=$PATH:/usr/local/bin" >> ~/.bashrc
            source ~/.bashrc
            sudo chmod +x /usr/local/bin/docker-compose
        - name: Fix Path
          run: |
            sudo echo "export PATH=$PATH:/usr/local/bin" >> ~/.bashrc
            source ~/.bashrc
        - name: Build 
          run: 
            docker-compose build 
        - name: UpCompose
          run: docker-compose up -d
